### PR TITLE
fix: use correct paths and module names to correctly execute Safe-DS files with spaces

### LINKED ISSUE #810: Error in execution of pipeline when space in file name
### Describe the bug

When pipeline contents are sent in a program message that come from a file that contains a space in it's name it throws the error seen in the Screenshot below. Namely "No module named a.gen_[file name with space]_mainpipeline".

### To Reproduce

1. create sdspipe file with space in name
2. include valid piepline code
3. sent with the executePipeline() method from DSL repository to python server (that is running of course)
4. Look at logs

### Expected behavior

That the pipeline executes like a pipeline from a file without a space in the name.

### Screenshots (optional)

WhatsApp Bild 2023-12-12 um 21 04 06_7eb5bf0e

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by WinPlay02**
Closes #810

### Summary of Changes

- fix: use correct paths and module names to correctly execute Safe-DS files that contain spaces and fix access to source mappings for these files

### CODE REVIEW

File: packages/safe-ds-vscode/src/extension/pythonServer.ts [hunk 1]
```diff
@@ -282,11 +282,23 @@ export const executePipeline = async function (services: SafeDsServices, pipelin
     }
     mainPipelineName = services.builtins.Annotations.getPythonName(firstPipeline) || firstPipeline.name;
     if (pipelinePath.endsWith('.sdspipe')) {
-        mainModuleName = path.basename(pipelinePath, '.sdspipe').replaceAll('-', '_');
+        mainModuleName = path
+            .basename(pipelinePath, '.sdspipe')
+            .replaceAll('%2520', '_')
+            .replaceAll(/[ .-]/gu, '_')
+            .replaceAll(/\\W/gu, '');
```
Comment (lars-reimann) [inline packages/safe-ds-vscode/src/extension/pythonServer.ts:289]: Extract this into a function.

File: packages/safe-ds-vscode/src/extension/pythonServer.ts [hunk 2]
```diff
@@ -297,17 +309,21 @@ export const executePipeline = async function (services: SafeDsServices, pipelin
...
-        const workspaceRelativeFilePath = path.relative(workspaceRoot, path.dirname(fsPath));
+
+        lastGeneratedSource.set(
+            path.join(workspaceRelativeFilePath, sdsFileName).replaceAll('\\', '/'),
+            generatedDocument.getText(),
+        );
+        if (fsPath.endsWith('.map')) {
+            // exclude sourcemaps from sending to runner
+            continue;
+        }
```
Comment (lars-reimann) [inline packages/safe-ds-vscode/src/extension/pythonServer.ts:326]: Is it possible to move this guard condition right behind the declaration of `fsPath` (i.e. line 312)? If its possible, move it please. Otherwise, add a comment why it must stay here.

**Review by lars-reimann — CHANGES_REQUESTED** [review]

File: packages/safe-ds-vscode/src/extension/pythonServer.ts (hunk 2 above)
Comment (WinPlay02) [reply packages/safe-ds-vscode/src/extension/pythonServer.ts:326]: If it was moved, the sourcemaps would not be stored in the pipeline context anymore. Errors would no longer be mapped. 
I'll add a comment

**Comment by lars-reimann** [comment]
@SmiteDeluxe Could you check whether this fixes the issue you reported?

File: packages/safe-ds-vscode/src/extension/pythonServer.ts (hunk 1 above)
Comment (WinPlay02) [reply packages/safe-ds-vscode/src/extension/pythonServer.ts:289]: As this was copied from the code generator, I'll add a helper function to the python generator that can be called here

**Review by SmiteDeluxe — APPROVED** [review]
Fixes my reported problem!

**Comment by SmiteDeluxe** [comment]
@lars-reimann still seems to want your review before being able to be merged!

**Review by lars-reimann — APPROVED** [review]
